version: '3.8'

services:
  postgres:
    container_name: picpay_postgres
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=picpay_db
